# Generated by Django 6.1.1 on 2026-09-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='client_digest',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'approved', 'created_at', 'id'], name='comment_public_page_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['client_digest', 'created_at'], name='comment_rate_limit_idx'),
        ),
    ]
