# Generated by Django 6.1.1 on 2026-09-27 11:23

import django.db.models.deletion
from django.db import migrations, models


def populate_word_counts(apps, schema_editor):
    Post = apps.get_model('blog_app', 'Post')
    posts = Post.objects.using(schema_editor.connection.alias)
    batch = []
    for post in posts.only('id', 'body').iterator(chunk_size=200):
        post.word_count = len(post.body.split())
        batch.append(post)
        if len(batch) == 200:
            posts.bulk_update(batch, ['word_count'])
            batch.clear()
    if batch:
        posts.bulk_update(batch, ['word_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_comment_client_digest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='blog_app.collection')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_entries', to='blog_app.post')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='posts',
            field=models.ManyToManyField(related_name='collections', through='blog_app.CollectionEntry', to='blog_app.post'),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=180)),
                ('is_open', models.BooleanField(default=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='blog_app.post')),
            ],
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='blog_app.poll')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_digest', models.CharField(editable=False, max_length=64)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='blog_app.pollchoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='blog_app.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('useful', 'Useful'), ('insightful', 'Insightful'), ('inspiring', 'Inspiring')], max_length=12)),
                ('reader_digest', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog_app.post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='collectionentry',
            constraint=models.UniqueConstraint(fields=('collection', 'post'), name='unique_collection_post'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('poll', 'reader_digest'), name='unique_reader_poll_vote'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['post', 'created_at'], name='reaction_activity_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('post', 'reader_digest'), name='unique_reader_reaction'),
        ),
        migrations.RunPython(populate_word_counts, migrations.RunPython.noop),
    ]
