# Generated by Django 6.1.1 on 2026-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_reader_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionQuota',
            fields=[
                ('key', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
